sonar.projectKey=nahushr_SuperDataGrid
sonar.organization=nahushr
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx
sonar.coverage.exclusions=src/**
sonar.sourceEncoding=UTF-8
